name: sheets
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  async: ^2.11.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.15
  google_fonts: ^6.2.1
  uuid: ^4.5.1
  intl: ^0.19.0
  visibility_detector: ^0.4.0+2
  html: ^0.15.5
  super_clipboard: ^0.8.24
  slang: ^4.4.0
  slang_flutter: ^4.4.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.14
  slang_build_runner: ^4.4.0

flutter:
  generate: true
  uses-material-design: true

  fonts:
    - family: GoogleSans
      fonts:
        - asset: assets/fonts/GoogleSans/GoogleSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/GoogleSans/GoogleSans-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/GoogleSans/GoogleSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/GoogleSans/GoogleSans-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/GoogleSans/GoogleSans-Bold.ttf
          weight: 600
        - asset: assets/fonts/GoogleSans/GoogleSans-BoldItalic.ttf
          weight: 600
          style: italic
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Thin.ttf
          weight: 100
        - asset: assets/fonts/Roboto/Roboto-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto/Roboto-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto/Roboto-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto/Roboto-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 600
        - asset: assets/fonts/Roboto/Roboto-BoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Roboto/Roboto-Black.ttf
          weight: 800
        - asset: assets/fonts/Roboto/Roboto-BlackItalic.ttf
          weight: 800
          style: italic

  assets:
    - assets/
    - assets/icons/
    - assets/fonts/
