name: sheets
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  async: ^2.11.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  rxdart: ^0.28.0
  uuid: ^4.5.1
  intl: ^0.19.0
  visibility_detector: ^0.4.0+2
  html: ^0.15.5

dev_dependencies:
  dartdoc: ^8.1.0
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: GoogleSans
      fonts:
        - asset: assets/fonts/GoogleSans/GoogleSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/GoogleSans/GoogleSans-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/GoogleSans/GoogleSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/GoogleSans/GoogleSans-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/GoogleSans/GoogleSans-Bold.ttf
          weight: 600
        - asset: assets/fonts/GoogleSans/GoogleSans-BoldItalic.ttf
          weight: 600
          style: italic

  assets:
    - assets/
    - assets/icons/
    - assets/fonts/
